version: "3.8"

services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - "8000:5000"
    volumes:
      - ./:/usr/src/app/

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      # You can set the value of environment variables
      # in your docker-compose.yml file
      # Our Node app will use these to connect
      # to the database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      # Standard port for PostgreSQL databases
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
